In [13]:
import torch

# 创建一个张量
x = torch.tensor([[1, 2], [3, 4]])

# 打印张量
print("CPU上的张量:")
print(x)
# 输出:
# CPU上的张量:
# tensor([[1, 2],
#         [3, 4]])


# 将张量移动到Mac的GPU（如果可用）
# ------------------------------------
# 检查MPS是否可用，而不是cuda
if torch.backends.mps.is_available():
    device = torch.device("mps") # 指定设备为mps
    print("Mac GPU (MPS) is available.")

    # 在GPU上创建一个与x形状相同的张量
    y = torch.ones_like(x, device=device)

    # 将x移动到GPU
    x = x.to(device)

    z = x + y

    # 打印GPU上的结果
    print("GPU上的张量相加结果:")
    print(z)
else:
    print("Mac GPU (MPS) is not available.")
    # 如果MPS不可用，代码将继续在CPU上运行
    z = x + torch.ones_like(x)
    print("GPU不可用，在CPU上计算结果:")
    print(z)

CPU上的张量:
tensor([[1, 2],
        [3, 4]])
Mac GPU (MPS) is available.
GPU上的张量相加结果:
tensor([[2, 3],
        [4, 5]], device='mps:0')
