In [4]:
import torch
x=torch.arange(12)
print(x)
print(x.shape)
x.numel()
x=x.reshape(3,4)
print(x)
x.numel()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


12

In [5]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 3, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  5.,  6., 10.]),
 tensor([-1., -1.,  2.,  6.]),
 tensor([ 2.,  6.,  8., 16.]),
 tensor([0.5000, 0.6667, 2.0000, 4.0000]),
 tensor([ 1.,  8., 16., 64.]))

In [6]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(X)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(Y)
torch.cat((X, Y), dim=0)
X==Y
X.sum()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor(66.)