In [7]:
"""
# PyTorch Tensor 基础语法示例
"""
import torch

# ---
# 张量创建
x=torch.tensor([1,2,3,4,5])
print(x)   # 直接从Python列表创建一维张量，元素为1,2,3
x=torch.zeros((2, 3))  # 创建一个2行3列的张量，所有元素为0
print(x)
torch.ones((2, 3))           # 创建一个2行3列的张量，所有元素为1
torch.full((2, 3), 7)        # 创建一个2行3列的张量，所有元素为7
torch.arange(0, 10, 2)       # 创建一个一维张量，元素为0到10（不含10），步长为2：0,2,4,6,8
torch.linspace(0, 1, 5)      # 创建一个一维张量，将区间[0,1]等分成5个点：0,0.25,0.5,0.75,1
torch.eye(3)                 # 创建一个3x3的单位矩阵（对角线为1，其余为0）
torch.randn(3, 4)            # 创建一个3行4列的张量，元素服从标准正态分布（均值0，方差1）
x=torch.normal(0, 1, (3, 4))   # 创建一个3x4的张量，元素服从均值为0、标准差为1的正态分布
print(x)

tensor([1, 2, 3, 4, 5])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 1.5826,  0.4617, -0.3415,  0.6517],
        [-0.3541,  1.0408,  2.7732,  2.6546],
        [-1.2316,  0.0519,  0.1857,  0.4020]])


In [ ]:
# ---
# 属性
t = torch.randn(4, 5)             # 创建一个4行5列的随机张量
print("shape:", t.shape)          # 打印张量的形状（即维度大小），如torch.Size([4, 5])
print("ndim:", t.ndim)            # 打印张量的维度数，这里为2
print("dtype:", t.dtype)          # 打印张量的数据类型（如float32等）
print("device:", t.device)        # 打印张量所在的设备（如cpu或cuda）

In [8]:
# ---
# 索引与切片
y = torch.arange(10)                 # 创建一个0~9的一维张量
print("y[2:5]:", y[2:5])             # 打印第2~4号元素（左闭右开），输出tensor([2, 3, 4])
m = torch.tensor([[1, 2, 3], [4, 5, 6]])   # 创建2x3的二维张量
print("m[1, :]:", m[1, :])            # 打印第1行的所有元素，输出tensor([4, 5, 6])


y[2:5]: tensor([2, 3, 4])
m[1, :]: tensor([4, 5, 6])


In [9]:
# ---
# 形状变换
p = torch.arange(6)                   # 创建0~5的一维张量
p1 = p.reshape(2, 3)                  # 改变形状为2行3列（不改变数据），返回新张量
p2 = p.view(3, 2)                     # 改变形状为3行2列（与reshape类似，但有些约束）
pT = p1.T                             # 转置操作，将行列互换
p3 = p1.unsqueeze(0)                  # 在第0维增加一维，形状变为(1,2,3)
p4 = p3.squeeze()                     # 去除所有为1的维度，变回(2,3)
print("reshape:", p1)                 # 打印reshape后的张量
print("view:", p2)                    # 打印view后的张量
print("transpose:", pT)               # 打印转置后的张量
print("unsqueeze:", p3.shape)         # 打印增加维度后的形状
print("squeeze:", p4.shape)           # 打印去除多余一维后的形状

reshape: tensor([[0, 1, 2],
        [3, 4, 5]])
view: tensor([[0, 1],
        [2, 3],
        [4, 5]])
transpose: tensor([[0, 3],
        [1, 4],
        [2, 5]])
unsqueeze: torch.Size([1, 2, 3])
squeeze: torch.Size([2, 3])


In [10]:

# ---
# 基本运算
a = torch.tensor([1., 2., 3.])                # 创建一维浮点张量a
b = torch.tensor([4., 5., 6.])                # 创建一维浮点张量b
print("加法:", a + b)                         # 张量逐元素加法，输出tensor([5., 7., 9.])
print("乘法:", a * b)                         # 张量逐元素乘法，输出tensor([ 4., 10., 18.])
M1 = torch.tensor([[1., 2.], [3., 4.]])       # 2x2矩阵
M2 = torch.tensor([[5., 6.], [7., 8.]])       # 2x2矩阵
print("矩阵乘法:", M1 @ M2)                   # 矩阵乘法，等价于torch.matmul(M1, M2)
print("sum:", a.sum())                        # 张量所有元素求和
print("mean:", a.mean())                      # 张量所有元素求均值
print("max:", a.max())                        # 张量最大值
print("argmin:", a.argmin())                  # 最小元素的索引

加法: tensor([5., 7., 9.])
乘法: tensor([ 4., 10., 18.])
矩阵乘法: tensor([[19., 22.],
        [43., 50.]])
sum: tensor(6.)
mean: tensor(2.)
max: tensor(3.)
argmin: tensor(0)


In [ ]:
# ---
# 广播机制
x = torch.ones(2, 3)                      # 创建2x3全1的张量
y = torch.arange(3)                       # 创建长度为3的张量
print("广播加法:", x + y)                  # 广播机制：y自动扩展为(2,3)，逐元素相加

In [ ]:
# ---
# 自动求导
v = torch.tensor([2.0, 3.0], requires_grad=True)  # 创建可自动求导的张量
f = (v ** 2).sum()                               # 计算f = v的平方的和
f.backward()                                     # 对f反向传播，计算v的梯度
print("v的梯度:", v.grad)                        # 打印v的梯度，等于df/dv = 2*v


In [2]:

# ---
# 小型线性回归练习
# y = Xw + b
X = torch.tensor([[1., 2.], [3., 4.]])     # 输入特征矩阵，2个样本，每个样本2维
w = torch.tensor([0.5, -1.0])             # 权重向量
b = torch.tensor(2.0)                     # 偏置项
y = X @ w + b                             # 线性回归计算：矩阵乘法加偏置
print("线性回归输出:", y)                  # 打印模型输出结果


shape: torch.Size([4, 5])
ndim: 2
dtype: torch.float32
device: cpu
y[2:5]: tensor([2, 3, 4])
m[1, :]: tensor([4, 5, 6])
reshape: tensor([[0, 1, 2],
        [3, 4, 5]])
view: tensor([[0, 1],
        [2, 3],
        [4, 5]])
transpose: tensor([[0, 3],
        [1, 4],
        [2, 5]])
unsqueeze: torch.Size([1, 2, 3])
squeeze: torch.Size([2, 3])
加法: tensor([5., 7., 9.])
乘法: tensor([ 4., 10., 18.])
矩阵乘法: tensor([[19., 22.],
        [43., 50.]])
sum: tensor(6.)
mean: tensor(2.)
max: tensor(3.)
argmin: tensor(0)
广播加法: tensor([[1., 2., 3.],
        [1., 2., 3.]])
v的梯度: tensor([4., 6.])
线性回归输出: tensor([ 0.5000, -0.5000])
