In [8]:
import torch
x=torch.tensor(2.0)
y=torch.tensor(3.0)
x+y,x-y,x*y,x/y,x**y

(tensor(5.), tensor(-1.), tensor(6.), tensor(0.6667), tensor(8.))

In [9]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [10]:
x[3],x[2],x[0]

(tensor(3), tensor(2), tensor(0))

In [11]:
len(x),x.shape

(4, torch.Size([4]))

In [15]:
a=torch.arange(20).reshape((4,5))
print(a)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


In [18]:
print(a.T)

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])


In [20]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B)
B == B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])